name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set username
        id: set-username
        run: echo "::set-output name=USERNAME::$(git config user.name)"

      - name: Update README
        run: sed -i 's/${rishisoni90}/'"${{ steps.set-username.outputs.USERNAME }}"/ README.md

      - name: Commit changes
        run: |
          git config --global user.email "soni.rishi16@outlook.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with dynamic username"
          git push
